apiVersion: v1
kind: Service
metadata:
  name: ml-serving-service
  namespace: default
  labels:
    app: ml-serving
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
    protocol: TCP
    name: ml-serving-http
  selector:
    app: ml-serving